### ISSUE TITLE
Clicking on card from /products/ while not logged in takes you to the login page

### ISSUE THREAD

**Issue by alaq** [bind-this/ethical-app-store#97]
* What is the expected behavior?
To be taken to the single product page
* What is the actual behavior?
Takes you to login page
* What steps reproduce the behavior?
- Don't be logged in
- go to /products/
- click on a card

**Comment by avill01** [comment]
This should be fixed when we have a Single Product component to go to, right now it just defaults to the last Route in the Switch as a fall back (Login)
